apiVersion: v1
kind: Pod                                                                                                                                                       
metadata:                                                                                                                                                       
  name: nginx-nfs-pod                                                                                                                                           
  labels:                                                                                                                                                       
    name: nginx-nfs-pod                                                                                                                                         
spec:                                                                                                                                                           
  containers:                                                                                                                                                   
    - name: nginx-nfs-pod                                                                                                                                       
      image: fedora/nginx                                                                                                                                       
      ports:                                                                                                                                                    
        - name: web                                                                                                                                             
          containerPort: 80                                                                                                                                     
      volumeMounts:                                                                                                                                            
        - name: vol-eodc                                                                                                                              
          mountPath: /eodc
        - name: vol-write
          mountPath: /write
  securityContext:
    supplementalGroups: [60028, 65534]
  volumes:
    - name: vol-eodc
      persistentVolumeClaim:
        claimName: pvc-eodc
    - name: vol-write
      persistentVolumeClaim:
        claimName: pvc-write