---
kind: Template
apiVersion: v1
metadata:
  name: dev-database
  annotations:
    openshift.io/display-name: dev-database
labels:
  application: dev-database
message: "The openEO template will be instantiated." 

parameters:
- name: SERVICE_PREFIX
  displayName: Service Prefix
  value: dev
  required: true
- name: SERVICE_NAME
  displayName: Service Name
  value: database
  required: true
### DATABASE ####
- name: POSTGRESQL_VERSION
  displayName: Version of PostgreSQL Image
  value: "9.5"
- name: MEMORY_LIMIT_POSTGRES
  displayName: Memory Limit
  value: 256Mi
  required: true
- name: DB_USER
  displayName: PostgreSQL Connection Username
  generate: expression
  from: users[A-Z0-9]{3}
  required: true
- name: DB_PASSWORD
  displayName: PostgreSQL Connection Password
  generate: expression
  from: "[a-zA-Z0-9]{16}"
  required: true
- name: DB_PORT
  displayName: Postgres Port
  value: "5432"
  required: true
- name: DB_NAME
  displayName: PostgreSQL Database Name
  value: users
  required: true
- name: STORAGE_CLASS
  displayName: Storage Class Name
  value: storage-write
  required: true
- name: VOLUME_CAPACITY_POSTGRES
  displayName: Volume Capacity
  value: 5Gi
  required: true

objects:
### DATABASE ####
- kind: Secret
  apiVersion: v1
  metadata:
    name: "${SERVICE_PREFIX}-${SERVICE_NAME}-db"
  stringData:
    database-user: "${DB_USER}"
    database-password: "${DB_PASSWORD}"
    database-port: "${DB_PORT}"
    database-name: "${DB_NAME}"

- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: "${SERVICE_PREFIX}-${SERVICE_NAME}-db"
    annotations:
      template.alpha.openshift.io/wait-for-ready: 'true'
    labels:
      name: "${SERVICE_PREFIX}-${SERVICE_NAME}-db"
      application: "${SERVICE_PREFIX}-${SERVICE_NAME}"
      provider: "${SERVICE_PREFIX}"
      project: "${SERVICE_PREFIX}"
      app: "${SERVICE_PREFIX}-${SERVICE_NAME}"
      version: 0.0.1
  spec:
    strategy:
      type: Recreate
    triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - postgresql
        from:
          kind: ImageStreamTag
          name: "postgresql:${POSTGRESQL_VERSION}"
          namespace: openshift
        lastTriggeredImage:
    - type: ConfigChange
    replicas: 1
    selector:
      name: "${SERVICE_PREFIX}-${SERVICE_NAME}-db"
    template:
      metadata:
        labels:
          name: "${SERVICE_PREFIX}-${SERVICE_NAME}-db"
      spec:
        containers:
        - name: postgresql
          image:
          ports:
          - containerPort: "${DB_PORT}"
            protocol: TCP
          readinessProbe:
            timeoutSeconds: 1
            initialDelaySeconds: 5
            exec:
              command:
              - "/bin/sh"
              - "-i"
              - "-c"
              - psql -h 127.0.0.1 -U $POSTGRESQL_USER -q -d $POSTGRESQL_DATABASE -c
                'SELECT 1'
          livenessProbe:
            timeoutSeconds: 1
            initialDelaySeconds: 30
            tcpSocket:
              port: 5432
          env:
          - name: POSTGRESQL_USER
            valueFrom:
              secretKeyRef:
                name: "${SERVICE_PREFIX}-${SERVICE_NAME}-db"
                key: database-user
          - name: POSTGRESQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: "${SERVICE_PREFIX}-${SERVICE_NAME}-db"
                key: database-password
          - name: POSTGRESQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: "${SERVICE_PREFIX}-${SERVICE_NAME}-db"
                key: database-name
          - name: POSTGRESQL_PORT
            valueFrom:
              secretKeyRef:
                name: "${SERVICE_PREFIX}-${SERVICE_NAME}-db"
                key: database-port
          resources:
            limits:
              memory: "${MEMORY_LIMIT_POSTGRES}"
          volumeMounts:
          - name: vol-${SERVICE_PREFIX}-${SERVICE_NAME}
            mountPath: "/var/lib/pgsql/data"
          terminationMessagePath: "/dev/termination-log"
          imagePullPolicy: IfNotPresent
        volumes:
        - name: vol-${SERVICE_PREFIX}-${SERVICE_NAME}
          persistentVolumeClaim:
            claimName: ${SERVICE_PREFIX}-${SERVICE_NAME}-db
        restartPolicy: Always
        dnsPolicy: ClusterFirst

- kind: Service
  apiVersion: v1
  metadata:
    name: "${SERVICE_PREFIX}-${SERVICE_NAME}-db"
  spec:
    ports:
    - name: postgresql
      protocol: TCP
      port: 5432
      targetPort: 5432
    selector:
      name: "${SERVICE_PREFIX}-${SERVICE_NAME}-db"

- kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    name: ${SERVICE_PREFIX}-${SERVICE_NAME}-db
  spec:
    storageClassName: "${STORAGE_CLASS}"
    accessModes:
    - ReadWriteOnce
    persistentVolumeReclaimPolicy: Recycle
    resources:
      requests:
        storage: "${VOLUME_CAPACITY_POSTGRES}"