apiVersion: v1
kind: PersistentVolume
metadata:
  name: vol-openeo-processes
spec:
  storageClassName: storage-write
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: $HOME/.oc/profiles/the-cluster-name/pv/openshift_vol_processes
