apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-0100
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs: 
    path: /nfs/pv0100
    server: 10.250.17.143